version: '3.7'
services:
  db:
    #platform: linux/x86_64 #workaround for mac M1 chips
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password

  db-setup:
    #platform: linux/x86_64 #workaround for mac M1 chips
    image: mysql:5.7
    depends_on:
      - db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: root
      MYSQL_PWD: password
    links:
      - db:mysqldb
    entrypoint: ["/bin/bash", "-c"]
    command:
      - |
        while true; do
            mysql -hmysqldb -u$$MYSQL_USER -p$$MYSQL_ROOT_PASSWORD mysql -e 'show tables;' >/dev/null 2>&1
            if [ $$? -eq 0 ]; then
                break
            fi
            echo "Waiting for db..."
            sleep 5
        done
        
        echo "Initializing db..."
        mysql -hmysqldb -u$$MYSQL_USER -p$$MYSQL_ROOT_PASSWORD mysql <<'EOF'
        CREATE DATABASE IF NOT EXISTS dev_posts;

        CREATE USER IF NOT EXISTS 'username'@'%' IDENTIFIED BY 'password';
        GRANT ALL PRIVILEGES ON *.* TO 'username'@'%';
        EOF
        
        echo "Done! list of users:"
        mysql -hmysqldb -u$$MYSQL_USER -p$$MYSQL_ROOT_PASSWORD mysql -e "select User from mysql.user;"
        
  posts-api:
    build:
        context: ./api/
        dockerfile: deploy/local/Dockerfile
    restart: unless-stopped
    depends_on:
      - db-setup
    ports:
      - "8080:8080"

  posts-web:
    build:
        context: ./fe/
        dockerfile: deploy/local/Dockerfile
    restart: unless-stopped
    environment:
      REACT_APP_API_URL: http://localhost:8080
    depends_on:
      - posts-api
    ports:
      - "80:80"